apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-converter
  template:
    metadata:
      labels:
        app: pdf-converter
    spec:
      containers:
      - name: pdf-converter
        image: your-registry/pdf-converter:latest
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "production" 